name:                pskt
version:             0.1.0.0
github:              "csicar/pskt"
license:             BSD3
author:              "Carsten Csiky"
maintainer:          "example@example.com"
copyright:           "2020 Carsten CSiky"

extra-source-files:
- README.md
- stack.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/andyarvanitis/purescript-native#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.8.2 && < 0.11
- purescript -any
- base-compat >=0.6.0
- protolude >=0.1.6
- text
- containers
- filepath
- monad-parallel >= 0.7.2.2 && <0.8
- pattern-arrows >=0.0.2 && <0.1
- safe >=0.3.9 && <0.4
- transformers >=0.3.0 && <0.6
- mtl >=2.1.0 && <2.3.0
- aeson >=1.0 && <1.5
- prettyprinter >= 1.3.0
- optparse-applicative >= 0.15.0
- pretty-simple >= 2.0.0
- Glob >= 0.7.0
- directory -any
- process -any
- file-embed -any
- gitrev -any
- recursion-schemes
- deriving-compat
- shake
- extra

library:
  source-dirs: src
  default-extensions:
    - ConstraintKinds
    - DataKinds
    - DeriveFunctor
    - EmptyDataDecls
    - FlexibleContexts
    - KindSignatures
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - PatternGuards
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - OverloadedStrings
    - FlexibleInstances
    - ScopedTypeVariables
    - TupleSections
    - ViewPatterns

executables:
  pskt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pskt

tests:
  pskt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pskt
    - hspec
